repos:
  - repo: local
    hooks:
      - id: ruff
        name: Ruff lint
        entry: ruff check .
        language: system
        pass_filenames: false
        types_or: [ python, pyi, jupyter ]
